name: Run end-to-end tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install all required dependecies
        run: npm install
        working-directory: ./e2e-tests
      
      - name: Build and start containers
        run: docker-compose up

      - name: Run all tests from 'cypress/e2e' folder
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          command: npx cypress run
          working-directory: ./e2e-tests
      
      - name: Stop containers
        run: docker-compose down
