name: Run end-to-end tests

on:
  workflow_dispatch:

jobs:
  tests-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install all required dependencies
        run: npm ci
        working-directory: ./e2e-tests
      
      - name: Build and start containers
        run: docker-compose up -d

      - name: Run all tests from 'cypress/e2e' folder
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          command: npx cypress run
          working-directory: ./e2e-tests

      - name: Stop containers
        run: docker-compose down
  
  test-results-upload:
    runs-on: ubuntu-latest
    needs: tests-execution
    if: always()
    steps:
      - name: Save Test Results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/screenshots

      - name: Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: cypress/reports/mochawesome/*.json
