# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 21:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, null=True, verbose_name='Extra data'),
        ),
    ]
